//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web;
using System.Web.UI;


namespace CastleBase
{


	public partial class Default : System.Web.UI.Page
	{
        protected void Page_Load(object sender, EventArgs e)
        {
			Response.Redirect("home/index.castle");	
		}
	}
}

